/* automatically generated by rust-bindgen */
#![allow(non_camel_case_types, dead_code)]
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int32_t = ::std::os::raw::c_int;
pub type sauchar_t = u8;
pub type saint_t = i32;
pub type saidx_t = i32;

#[link(name = "divsufsort", kind = "static")]
extern "C" {
    pub fn divsufsort(T: *const sauchar_t, SA: *mut saidx_t, n: saidx_t) -> saint_t;
    pub fn divbwt(T: *const sauchar_t, U: *mut sauchar_t, A: *mut saidx_t, n: saidx_t) -> saidx_t;
    pub fn bw_transform(
        T: *const sauchar_t,
        U: *mut sauchar_t,
        SA: *mut saidx_t,
        n: saidx_t,
        idx: *mut saidx_t,
    ) -> saint_t;
    pub fn inverse_bw_transform(
        T: *const sauchar_t,
        U: *mut sauchar_t,
        A: *mut saidx_t,
        n: saidx_t,
        idx: saidx_t,
    ) -> saint_t;
}
